# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_helper.py

import os

block_cipher = None
project_root = os.path.abspath(SPECPATH)

a = Analysis(
    ['run_gui.py'],
    pathex=[project_root],
    binaries=[],
    datas=[],
    hiddenimports=['PIL', 'PIL._imaging', 'PyInstaller', 'argparse', 'base64', 'bs4', 'chm', 'chm.chmlib', 'customtkinter', 'dataclasses', 'graph', 'io', 'lxml', 'lxml._elementpath', 'lxml.etree', 'os', 'pathlib', 'playwright', 'playwright._impl._browser', 'playwright._impl._browser_context', 'playwright._impl._driver', 'playwright._impl._page', 'playwright.sync_api', 'pypdf', 'shutil', 'subprocess', 'sys', 'tempfile', 'tkinter', 'typing'],
    hookspath=[os.path.join(project_root, 'hooks')],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter.test', 'unittest', 'email', 'xmlrpc', 'pydoc', 'doctest', 'matplotlib', 'numpy.tests', 'pytest', 'setuptools'],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SmartCHM2PDF',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    
)
